DATA SEGMENT
    LED DB 3FH, 06H, 5BH, 4FH, 66H, 6DH, 7DH, 07H
    	DB 7FH, 67H, 77H, 7CH, 39H, 5EH, 79H, 71H 
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX
    
    MOV DX, E48BH ;SHOULD CHANGE THE ADDRESS OF CONTRAL PORT
    MOV AL, 89H
    OUT DX, AL
    
INOUT:
	XOR AX, AX    ;SET AX TO ZERO
	MOV DX, E48AH ;SHOULD BE THE ADDRESS OF PORT C
	IN AL, DX
	
	MOV BL, AL    ;COPY
	AND BL, 0F0H
	AND AL, 0FH
	SHR BL, 4
	ADD AL, BL
	DAA
	MOV BL, AL
	AND BL, 10H
	CMP BL, 0H
	JZ OVER
	
	MOV CL, AL     ;COPY AL
	MOV AL, 1H
	MOV BX, OFFSET LED
	XLAT
	MOV DX, E48BH ;SHOULD BE THE ADDRESS OF PORT A
	OUT DX, AL
	
OVER:	
	MOV AL, CL
	AND AL, 0FH
	MOV BX, OFFSET LED
	XLAT
	MOV DX, E48BH ;SHOULD BE THE ADDRESS OF PORT A
	OUT DX, AL
	
	MOV AH, 1
	INT 16H
	JZ INOUT
    
    MOV AH,4CH
    INT 21H
CODE ENDS
    END START

